name: Deploy to Firebase Functions on PR
"on": pull_request
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install npm packages
        working-directory: ./functions
        run: |
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project=dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
